// Generated by CoffeeScript 1.7.1

/*
 * ----------------------------------------------
 * Authors:
 *   Emil Löfquist (emil.lofquist@mynewsdesk.com)
 *   Zoee Silcock (zoee.silcock@mynewsdesk.com)
 *
 * API docs:
 *   https://developers.google.com/youtube/iframe_api_reference
 * ----------------------------------------------
 */

(function() {
  var Mixin, Observable, YouTubeIframePlayer, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Mixin = (function() {
    function Mixin() {}

    Mixin.addTo = function(obj) {
      var method, name, _results;
      _results = [];
      for (name in this) {
        method = this[name];
        _results.push(obj[name] = method);
      }
      return _results;
    };

    return Mixin;

  })();

  Observable = (function(_super) {
    var eventListeners;

    __extends(Observable, _super);

    function Observable() {
      return Observable.__super__.constructor.apply(this, arguments);
    }

    eventListeners = [];

    Observable.on = function(to, onNewEvent) {
      return eventListeners.push({
        item: to,
        callback: onNewEvent
      });
    };

    Observable.notifyNewEvent = function(item, data) {
      var subscriber, _i, _len, _results;
      if (data == null) {
        data = {};
      }
      _results = [];
      for (_i = 0, _len = eventListeners.length; _i < _len; _i++) {
        subscriber = eventListeners[_i];
        if (subscriber.item === item) {
          _results.push(subscriber.callback(item, data));
        }
      }
      return _results;
    };

    return Observable;

  })(Mixin);

  YouTubeIframePlayer = (function() {
    var getNewHeight, insertApi, isZeroOrEmpty, resizeIframe;

    YouTubeIframePlayer.prototype.player = null;

    YouTubeIframePlayer.prototype.isPlaying = false;

    function YouTubeIframePlayer(playerContainerId, videoId, width, height, playerVars, responsiveIframe, resizeTimeout) {
      if (width == null) {
        width = 560;
      }
      if (height == null) {
        height = 315;
      }
      if (playerVars == null) {
        playerVars = {};
      }
      if (responsiveIframe == null) {
        responsiveIframe = false;
      }
      if (resizeTimeout == null) {
        resizeTimeout = 100;
      }
      this.respondToResize = __bind(this.respondToResize, this);
      if (typeof YT === "undefined" || YT === null) {
        insertApi();
      }
      Observable.addTo(this);
      this.playerContainerId = playerContainerId;
      this.videoId = videoId;
      this.width = width;
      this.height = height;
      this.playerVars = playerVars;
      this.responsiveIframe = responsiveIframe;
      this.resizeTimeout = resizeTimeout;
    }

    YouTubeIframePlayer.prototype.insertPlayer = function() {
      return this.player = new YT.Player(this.playerContainerId, {
        width: this.width,
        height: this.height,
        videoId: this.videoId,
        playerVars: this.playerVars,
        events: {
          onReady: (function(_this) {
            return function() {
              _this.notifyNewEvent('ready');
              if (_this.responsiveIframe) {
                return _this.respondToResize();
              }
            };
          })(this),
          onError: (function(_this) {
            return function(e) {
              var message;
              switch (e.data) {
                case 2:
                  message = "Incorrect parameter value.";
                  break;
                case 5:
                  message = "Content cannot be played in a HTML5 player or a HTML5 player related error has occured.";
                  break;
                case 100:
                  message = "The video requested cannot be found.";
                  break;
                case 101:
                case 150:
                  message = "The owner of the requested video does not allow it to be played in embedded players.";
              }
              return _this.notifyNewEvent('error', {
                code: e.data,
                message: message
              });
            };
          })(this),
          onPlaybackRateChange: (function(_this) {
            return function(e) {
              return _this.notifyNewEvent('playbackRateChange', e.data);
            };
          })(this),
          onPlaybackQualityChange: (function(_this) {
            return function(e) {
              return _this.notifyNewEvent('playbackQualityChange', e.data);
            };
          })(this),
          onApiChange: (function(_this) {
            return function(e) {
              return _this.notifyNewEvent('apiChange', e.data);
            };
          })(this),
          onStateChange: (function(_this) {
            return function(e) {
              switch (e.data) {
                case YT.PlayerState.UNSTARTED:
                  return _this.notifyNewEvent('unstarted', e.data);
                case YT.PlayerState.ENDED:
                  return _this.notifyNewEvent('ended', e.data);
                case YT.PlayerState.PLAYING:
                  if (_this.isPlaying) {
                    return _this.notifyNewEvent('seeking', e.data);
                  } else {
                    _this.isPlaying = true;
                    return _this.notifyNewEvent('playing', e.data);
                  }
                  break;
                case YT.PlayerState.PAUSED:
                  return _this.notifyNewEvent('paused', e.data);
                case YT.PlayerState.BUFFERING:
                  return _this.notifyNewEvent('buffering', e.data);
                case YT.PlayerState.CUED:
                  return _this.notifyNewEvent('cued', e.data);
              }
            };
          })(this)
        }
      });
    };

    insertApi = function() {
      var firstScriptTag, script;
      script = document.createElement('script');
      script.src = 'https://www.youtube.com/iframe_api';
      firstScriptTag = document.getElementsByTagName('script')[0];
      return firstScriptTag.parentNode.insertBefore(script, firstScriptTag);
    };

    getNewHeight = function(originalWidth, originalHeight, newWidth) {
      return Math.round(originalHeight / originalWidth * newWidth);
    };

    isZeroOrEmpty = function(val) {
      return val === "0" || val === "";
    };

    resizeIframe = function(iframe) {
      var height, newHeight, parent, parentWidth, width;
      width = iframe.width;
      height = iframe.height;
      parent = iframe.parentNode;
      parentWidth = parent.offsetWidth;
      newHeight = getNewHeight(width, height, parentWidth);
      if (!(isZeroOrEmpty(parent.style.opacity) || isZeroOrEmpty(parent.style.height))) {
        parent.style.height = "" + newHeight + "px";
      }
      iframe.style.width = "" + parentWidth + "px";
      return iframe.style.height = "" + newHeight + "px";
    };

    YouTubeIframePlayer.prototype.respondToResize = function() {
      var iframe, timer;
      iframe = this.player.getIframe();
      resizeIframe(iframe);
      timer = null;
      return window.onresize = (function(_this) {
        return function() {
          clearTimeout(timer);
          return timer = setTimeout(function() {
            return resizeIframe(iframe);
          }, _this.resizeTimeout);
        };
      })(this);
    };

    return YouTubeIframePlayer;

  })();

  root.YouTubeIframePlayer = YouTubeIframePlayer;

}).call(this);
