// Generated by CoffeeScript 1.7.1
(function() {
  $.fn.extend({
    youtubeIframe: function(options) {
      var settings;
      settings = {
        videoId: null,
        width: 560,
        height: 315,
        playerVars: {},
        responsiveiframe: false,
        resizeTimeout: 100,
        onReady: function() {},
        onError: function() {},
        onPlaybackRateChange: function() {},
        onPlaybackQualityChange: function() {},
        onApiChange: function() {},
        onUnstarted: function() {},
        onEnd: function() {},
        onPlaying: function() {},
        onPaused: function() {},
        onBuffering: function() {},
        onCued: function() {}
      };
      settings = $.extend(settings, options);
      return this.each(function() {
        var containerId, data, player;
        if (!$.isEmptyObject($(this).data())) {
          data = $(this).data();
          data.playerVars = {};
          settings = $.extend(settings, data);
        }
        containerId = "video-" + settings.videoId;
        $(this).attr('id', containerId);
        player = new YouTubeIframePlayer(containerId, settings.videoId, settings.width, settings.height, settings.playerVars, settings.responsiveIframe, settings.resizeTimeout);
        player.on('ready', function() {
          return settings.onReady();
        });
        player.on('ended', function() {
          return settings.onEnd();
        });
        player.on('playing', function() {
          return settings.onPlaying();
        });
        return player.on('paused', function() {
          return settings.onPaused();
        });
      });
    }
  });

}).call(this);
